# Generated by Django 5.2.6 on 2026-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
