# Generated by Django 5.2.6 on 2025-09-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmailTemplates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
