# Generated by Django 5.2.6 on 2025-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmailTemplates", "0002_alter_template_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="no_of_time_used",
            field=models.IntegerField(default=0),
        ),
    ]
