# Generated by Django 5.2.6 on 2026-05-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailTemplates', '0003_template_no_of_time_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
