# Generated by Django 5.2.6 on 2025-09-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="emailUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("email_password", models.CharField(max_length=200)),
                (
                    "email_host",
                    models.CharField(default="smtp.gmail.com", max_length=100),
                ),
                ("email_port", models.IntegerField(default=587)),
                ("use_tls", models.BooleanField(default=True)),
                ("login_password", models.CharField(default="test1234", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Receipent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(default="Customer", max_length=150)),
                (
                    "Sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CreateUser.emailusers",
                    ),
                ),
            ],
        ),
    ]
