# Generated by Django 5.2.6 on 2025-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipent",
            name="email",
            field=models.CharField(max_length=200),
        ),
    ]
