# Generated by Django 5.2.6 on 2025-09-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0002_alter_receipent_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailusers",
            name="about_you",
            field=models.CharField(default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="emailusers",
            name="address",
            field=models.CharField(default="", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="emailusers",
            name="department",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="emailusers",
            name="dob",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="emailusers",
            name="fatherName",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="emailusers",
            name="personalEmail",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="emailusers",
            name="post",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
