# Generated by Django 5.2.6 on 2025-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0003_emailusers_about_you_emailusers_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailusers",
            name="image",
            field=models.ImageField(default="default.png", upload_to="images/"),
        ),
    ]
