# Generated by Django 5.2.6 on 2025-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0004_emailusers_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailusers",
            name="dob",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
