# Generated by Django 5.2.6 on 2025-09-15 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0005_alter_emailusers_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailusers",
            name="dob",
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
