# Generated by Django 5.2.6 on 2025-09-15 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0006_alter_emailusers_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="reset_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=50, null=True)),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("new_password", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CreateUser.emailusers",
                    ),
                ),
            ],
        ),
    ]
