# Generated by Django 5.2.6 on 2025-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0007_reset_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="reset_link",
            name="is_attempted",
            field=models.BooleanField(default=False),
        ),
    ]
