# Generated by Django 5.2.6 on 2025-09-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0008_reset_link_is_attempted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reset_link",
            old_name="date",
            new_name="datetime",
        ),
    ]
