# Generated by Django 5.2.6 on 2025-09-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0009_rename_date_reset_link_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipent",
            name="comment",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="receipent",
            name="receipent_category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
