# Generated by Django 5.2.6 on 2025-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0010_receipent_comment_receipent_receipent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipent",
            name="added_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
