# Generated by Django 5.2.6 on 2025-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0011_receipent_added_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipent",
            name="send_time",
            field=models.IntegerField(default=0),
        ),
    ]
