# Generated by Django 5.2.6 on 2025-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0012_receipent_send_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailusers",
            name="email_password",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="emailusers",
            name="email_port",
            field=models.IntegerField(default=587, null=True),
        ),
        migrations.AlterField(
            model_name="emailusers",
            name="image",
            field=models.ImageField(
                default="default.png", null=True, upload_to="images/"
            ),
        ),
    ]
