# Generated by Django 5.2.6 on 2025-09-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0013_alter_emailusers_email_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailusers",
            name="fatherName",
        ),
    ]
