# Generated by Django 5.2.6 on 2025-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0014_remove_emailusers_fathername"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailusers",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
