# Generated by Django 5.2.6 on 2025-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0015_emailusers_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailusers",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
