# Generated by Django 5.2.6 on 2025-09-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0016_alter_emailusers_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailusers",
            name="dob",
            field=models.DateField(null=True),
        ),
    ]
