# Generated by Django 5.2.6 on 2025-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0017_alter_emailusers_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailusers",
            name="org_name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
