# Generated by Django 5.2.6 on 2025-09-24 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0018_emailusers_org_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("file_size", models.CharField(max_length=50)),
                ("file_type", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="user_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CreateUser.emailusers",
                    ),
                ),
            ],
        ),
    ]
