# Generated by Django 5.2.6 on 2025-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0019_userfiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfiles",
            name="file",
            field=models.FileField(upload_to="Receipients_files/"),
        ),
    ]
