# Generated by Django 5.2.6 on 2025-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0020_alter_userfiles_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipent",
            name="source",
            field=models.CharField(default="Manually Added", max_length=100, null=True),
        ),
    ]
