# Generated by Django 5.2.6 on 2025-09-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CreateUser", "0021_receipent_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipent",
            name="source",
            field=models.CharField(default="N/A", max_length=100, null=True),
        ),
    ]
