# Generated by Django 5.2.6 on 2025-10-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0022_alter_receipent_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipent_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('receipent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateUser.receipent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateUser.emailusers')),
            ],
        ),
    ]
