# Generated by Django 5.2.6 on 2025-10-11 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0023_receipent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipent_group',
            name='receipent',
        ),
        migrations.AddField(
            model_name='receipent',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CreateUser.receipent_group'),
        ),
    ]
