# Generated by Django 5.2.6 on 2025-10-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0024_remove_receipent_group_receipent_receipent_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipent',
            name='receipent_category',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
    ]
