# Generated by Django 5.2.6 on 2026-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0025_alter_receipent_receipent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailusers',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emailusers',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailusers',
            name='api_usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
